name: contact_picker_example
description: Demonstrates how to use the contact_picker plugin.

dependencies:
  simple_permissions: ^0.1.6
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  contact_picker:
    path: ../

flutter:
  uses-material-design: true
