name: contact_picker
description: A Flutter plugin for picking a contact from the address book.
version: 0.0.5
authors:
  - Michael Goderbauer <michael@goderbauer.net>
  - Rody Davis <rody.davis.jr@gmail.com>
homepage: https://github.com/appleeducate/contact_picker

flutter:
  plugin:
    androidPackage: com.appleeducate.flutter.contactpicker
    pluginClass: ContactPickerPlugin

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
